wandb_version: 1

alpha:
  value: 0.1
batch_size:
  value: 8
bottleneck-dim:
  value: 128
epochs:
  value: 30
finetune:
  value: false
gl:
  value: cool
grl:
  value: constant
lambda_c:
  value: 1
lambda_d:
  value: 0.1
lr:
  value: 0.001
lr-decay:
  value: 0.132298361253254
max_iters:
  value: 1083
weight-decay:
  value: 0.01
