wandb_version: 1

alpha:
  value: 1
batch_size:
  value: 16
bottleneck-dim:
  value: 256
epochs:
  value: 60
finetune:
  value: true
gl:
  value: cool
grl:
  value: constant
lambda_c:
  value: 1
lambda_d:
  value: 1
lr:
  value: 0.001
lr-decay:
  value: 0.620626033242329
max_iters:
  value: 4335
weight-decay:
  value: 0.1
