wandb_version: 1

alpha:
  value: 1
batch_size:
  value: 64
bottleneck_dim:
  value: 1024
epochs:
  value: 1
finetune:
  value: false
gl:
  value: constant
grl:
  value: warm
lambda_c:
  value: 1
lambda_d:
  value: 10
lr:
  value: 0.001
lr_decay:
  value: 0.535623597656183
max_iters:
  value: 9754
weight_decay:
  value: 0.001
