wandb_version: 1

alpha:
  value: 100
batch_size:
  value: 64
bottleneck_dim:
  value: 128
epochs:
  value: 1
finetune:
  value: false
gl:
  value: constant
grl:
  value: constant
lambda_c:
  value: 1
lambda_d:
  value: 5
lr:
  value: 0.001
lr_decay:
  value: 0.21188836145919343
max_iters:
  value: 9485
weight_decay:
  value: 0.1
