wandb_version: 1

alpha:
  value: 0.1
batch_size:
  value: 32
bottleneck_dim:
  value: 1024
epochs:
  value: 1
finetune:
  value: true
gl:
  value: constant
grl:
  value: constant
lambda_c:
  value: 1
lambda_d:
  value: 2
lr:
  value: 0.001
lr_decay:
  value: 0.3654695433998295
max_iters:
  value: 1268
weight_decay:
  value: 0.1
