wandb_version: 1

alpha:
  value: 100
batch_size:
  value: 8
bottleneck_dim:
  value: 256
epochs:
  value: 1
finetune:
  value: true
gl:
  value: constant
grl:
  value: warm
lambda_c:
  value: 1
lambda_d:
  value: 1
lr:
  value: 0.001
lr_decay:
  value: 0.9470043632455604
max_iters:
  value: 9016
weight_decay:
  value: 0.01
