wandb_version: 1

alpha:
  value: 100
batch_size:
  value: 128
bottleneck_dim:
  value: 1024
epochs:
  value: 1
finetune:
  value: false
gl:
  value: constant
grl:
  value: warm
lambda_c:
  value: 1
lambda_d:
  value: 0.5
lr:
  value: 0.001
lr_decay:
  value: 0.10766190112076623
max_iters:
  value: 1574
weight_decay:
  value: 0.001
