wandb_version: 1

alpha:
  value: 0.1
batch_size:
  value: 128
bottleneck_dim:
  value: 128
epochs:
  value: 1
finetune:
  value: false
gl:
  value: constant
grl:
  value: warm
lambda_c:
  value: 1
lambda_d:
  value: 2
lr:
  value: 0.001
lr_decay:
  value: 0.14061659340194022
max_iters:
  value: 7718
weight_decay:
  value: 0.01
