wandb_version: 1

alpha:
  value: 0.1
batch_size:
  value: 16
bottleneck_dim:
  value: 256
epochs:
  value: 1
finetune:
  value: false
gl:
  value: constant
grl:
  value: constant
lambda_c:
  value: 1
lambda_d:
  value: 10
lr:
  value: 0.001
lr_decay:
  value: 0.07928451192476382
max_iters:
  value: 6944
weight_decay:
  value: 0.001
