wandb_version: 1

alpha:
  value: 10
batch_size:
  value: 8
bottleneck-dim:
  value: 512
epochs:
  value: 120
finetune:
  value: true
gl:
  value: constant
grl:
  value: warm
lambda_c:
  value: 1
lambda_d:
  value: 10
lr:
  value: 0.01
lr-decay:
  value: 0.6019351757307108
max_iters:
  value: 5950
weight-decay:
  value: 0.001
