wandb_version: 1

alpha:
  value: 100
batch_size:
  value: 16
bottleneck-dim:
  value: 256
epochs:
  value: 30
finetune:
  value: false
gl:
  value: constant
grl:
  value: constant
lambda_c:
  value: 1
lambda_d:
  value: 0.1
lr:
  value: 0.001
lr-decay:
  value: 0.7608371026963162
max_iters:
  value: 216
weight-decay:
  value: 0.001
